//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class score
{
    public int stuid { get; set; }
    public int chinese { get; set; }
    public int mathematics { get; set; }
    public Nullable<int> totalscore { get; set; }

    public virtual student1 student1 { get; set; }
}

public partial class student1
{
    public int stuid { get; set; }
    public string stuname { get; set; }
    public string stusex { get; set; }
    public int stuage { get; set; }

    public virtual score score { get; set; }
}

public partial class teacher
{
    public int teaid { get; set; }
    public string teaname { get; set; }
    public string teasex { get; set; }
    public int teaage { get; set; }
    public string course { get; set; }
}
